version: "3.9"
services:
  ros1:
    image: hero_common:ros1-noetic
    container_name: hero_ros_noetic
    build:
      context: ./
      dockerfile: ros1.dockerfile
    network_mode: host
    environment:
      - DISPLAY
      - PYTHONUNBUFFERED=1
      - HERO_SIM=0
    ipc: none
    volumes:
    - $HOME/.Xauthority:/root/.Xauthority:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    privileged: true # required for gazebo/rviz
    command: /bin/bash -c '. /opt/ros/noetic/setup.bash && . /catkin_ws/devel/setup.bash && roslaunch hero_bringup hero_bringup.launch'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ros2:
    image: hero_common:ros2-foxy
    container_name: hero_ros_foxy
    build:
      context: ./
      dockerfile: ros2.dockerfile
    command: watch ros2 topic list

  bridge:
    image: ros:foxy-ros1-bridge
    # environment:
      # - "ROS_HOSTNAME=bridge"
      # - "ROS_MASTER_URI=http://127.0.0.1:11311"
    command: /bin/bash -c '. /opt/ros/foxy/setup.bash && . /opt/ros/noetic/setup.bash && ros2 run ros1_bridge dynamic_bridge --bridge-all-topics'

  # bridge:
  #   image: hero_common:ros2-foxy
  #   container_name: hero_ros1_ros2_bridge
  #   environment:
  #     - "ROS_HOSTNAME=bridge"
  #     - "ROS_MASTER_URI=http://ros1:11311"
  #   command: ros2 run ros1_bridge dynamic_bridge